### ISSUE TITLE
Problem with Applications crashing

### ISSUE THREAD

**Issue by ctaylor2324** [AdobeDocs/cloudmanager-api-docs#1]
### Documentation Location

Using a MacBook Pro with the latest operating system installed, all Adobe applications keep crashing (installed from Cloud Manager). We have had this issue in the past, but it was resolved with updating the OS to its latest version. However, the problem has arose again. We spoke with Apple and they directed us to work with the developers to find a compatible version. ### Issue Description

**Comment by justinedelson** [comment]
Cloud Manager does not install desktop applications. I think you have this confused with something else.
