### ISSUE TITLE
Pagination start parameter should be type integer instead of string

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#11]
E.g. in https://www.adobe.io/apis/experiencecloud/cloud-manager/api-reference.html#/Pipeline_Execution/getExecutions the `limit` parameter is `integer` while the `start` parameter is `string`. IMHO both should be of the same type `integer`

This would also be in line with the response type in https://github.com/AdobeDocs/cloudmanager-api-docs/blob/232bfdf117055fc2d9843b3fd970cdc50f2cf83e/swagger-specs/api.yaml#L2008.

**Comment by justinedelson** [comment]
The swagger is a correct representation of the API here.

**Comment by kwin** [comment]
How can the request accept a non-numerical string if the response returns the start parameter as integer (https://github.com/AdobeDocs/cloudmanager-api-docs/blob/232bfdf117055fc2d9843b3fd970cdc50f2cf83e/swagger-specs/api.yaml#L2008)? How will the conversion be performed for non-numerical characters then?

**Comment by justinedelson** [comment]
There is a bit of future-proofing going on here -- the start parameter may, in the future, accept semantically meaningful string values.

**Comment by kwin** [comment]
I do understand, but then the response format should be changed accordingly (not really backwards compatible I fear).

**Comment by justinedelson** [comment]
Well, in the case where such semantic values are passed, the response would be the "actual" start index.

But yeah, backwards compatibility would be the bigger issue.
