### ISSUE TITLE
PipelineExecutionStepState should expose environment id in addition to label

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#16]
Currently the object `PipelineExecutionStepState` only exposes some environment label with https://github.com/AdobeDocs/cloudmanager-api-docs/blob/38265737eb4ac3bd54fa4324094e962f8017dc1c/swagger-specs/api.yaml#L1689. This is only useful for UI purposes, but not for follow-up API calls like https://github.com/AdobeDocs/cloudmanager-api-docs/blob/38265737eb4ac3bd54fa4324094e962f8017dc1c/swagger-specs/api.yaml#L1086 which requires the `environmentId`. Looking up the `environmentId` for a specific phase currently requires an additional call to https://github.com/AdobeDocs/cloudmanager-api-docs/blob/38265737eb4ac3bd54fa4324094e962f8017dc1c/swagger-specs/api.yaml#L269 to figure out the connected environment id.

It would be nice to expose the `environmentId` in addition also in `PipelineExecutionStepState` to not be forced to do an additional API call for e.g. calling the logs related to failed "deploy" phase.

**Comment by kwin** [comment]
Actually `PipelineExecutionStepState` only has identifier `phaseId` which is not used in `PipelinePhase`, therefore currently there is no way to do the mapping between `PipelineExecutionStepState` and the environmentId!

**Comment by justinedelson** [comment]
This has been corrected -- there is an `environmentId` property on the step state that was missing for some reason.
