### ISSUE TITLE
Expose pod name in PipelineExecutionStepState details

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#19]
Failures in the "deploy" step are hard to debug because often the error message is only visible in the [service's log](https://docs.adobe.com/content/help/en/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/logs.html). To be able to filter the environment log for relevant entries one needs to know the pod name. That is unfortunately not exposed in https://github.com/AdobeDocs/cloudmanager-api-docs/blob/b6c0678a414f112dba41e3bc8ecbf324385cd20f/swagger-specs/api.yaml#L1671

Although in one step there might be different pods involved usually only the pod where the error occurred is of interest. Instead of just the pod name also the complete podId could be exposed.

**Comment by justinedelson** [comment]
The documentation is correct here.

**Comment by kwin** [comment]
@justinedelson Do you want me to report that issue through some other channel then?

**Comment by justinedelson** [comment]
@kwin This project should only be used for documentation issues. In this case, the PipelineExecutionStepState documentation is correct. Feature requests for the API (or CM in general) should flow through the normal channels.
