### ISSUE TITLE
need adobe creative cloud api documentation 

### ISSUE THREAD

**Issue by ANKITSONI1** [AdobeDocs/cloudmanager-api-docs#2]
### Documentation Location
Appdirect
### Issue Description

I need complete API documentation for adobe creative cloud for our internal project development.
I want all updates on asset and folder
Receive updates on assets
Receive updates on folders

**Comment by justinedelson** [comment]
This is not the project for creative cloud documentation. I believe that is https://github.com/AdobeDocs/creative-sdk
