### ISSUE TITLE
body parameter in pipeline step advance / cancel must be type string

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#22]
Currently the `body` parameter in advance (https://github.com/AdobeDocs/cloudmanager-api-docs/blob/b6c0678a414f112dba41e3bc8ecbf324385cd20f/swagger-specs/api.yaml#L619) and cancel (https://github.com/AdobeDocs/cloudmanager-api-docs/blob/b6c0678a414f112dba41e3bc8ecbf324385cd20f/swagger-specs/api.yaml#L685) is defined as type `object` but according to <https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/advancing-and-cancelling-steps.md> this seems to be a JSON string.

**Comment by justinedelson** [comment]
I'm not sure I follow. https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/advancing-and-cancelling-steps.md shows the body objects. You're right that in a sense they're all strings since they're really all objects _serialized_ as strings, but that's what the Content-Type header is for.

**Comment by kwin** [comment]
If you generate a Java client with https://swagger.io/tools/swagger-codegen/ the following method is generated

```    /**
     * Cancel
     * Post to this url in order to cancel the current pipeline execution. Link is present in output only in that case.
     * @param programId Identifier of the program. (required)
     * @param pipelineId Identifier of the pipeline (required)
     * @param executionId Identifier of the execution (required)
     * @param phaseId Identifier of the phase (required)
     * @param stepId Identifier of the step (required)
     * @param body Input for cancel. See documentation at https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/advancing-and-cancelling-steps.md for details. (required)
     * @param xGwImsOrgId IMS organization ID that the request is being made under. (required)
     * @param authorization Bearer [token] - An access token for the technical account created through integration with Adobe IO (required)
     * @param xApiKey IMS Client ID (API Key) which is subscribed to consume services on console.adobe.io (required)
     * @param contentType Must always be application/json (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void cancelPipelineExecutionStep(String programId, String pipelineId, String executionId, String phaseId, String stepId, Object body, String xGwImsOrgId, String authorization, String xApiKey, String contentType) throws ApiException {
        cancelPipelineExecutionStepWithHttpInfo(programId, pipelineId, executionId, phaseId, stepId, body, xGwImsOrgId, authorization, xApiKey, contentType);
    }```

Although obviously everything is an object, it would be nice to have a higher level abstraction here (at least string).

**Comment by kwin** [comment]
In the best case the swagger API spec would be provided in version 3. Then `anyOf` would be allowed (https://swagger.io/docs/specification/describing-request-body/) and the body could be described by 3 different models.

**Comment by justinedelson** [comment]
I don't think `string` would be semantically correct.
