### ISSUE TITLE
Explain Variable Type "secretString"

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#26]
Currently at https://github.com/AdobeDocs/cloudmanager-api-docs/blob/d9cbdcdac0fdf156501f4dbcc1b3addaf78dd46c/swagger-specs/api.yaml#L2177 it only states

> `secretString` variables are encrypted at rest. Cannot be changed after creation.

The first sentence is rather vague, the following questions should be answered:

1. Is the secret variable written to a file? If yes, with which charset and at which path?
2. How is the variable being encrypted, how can one read from it then?
3. What does `Cannot be changed after creation.` mean? Can I ever get rid of a previously set secret? If so how?

**Comment by justinedelson** [comment]
1. This is an implementation detail.
2. This is also an implementation detail -- consuming applications do not read these variables directly (nor are they responsible for decryption).
3. This means that the *type* cannot be changed, i.e. you can't convert a `string` type variable into a `secretString` type variable. But I see how the string (no pun intended) of sentences here makes this confusing. Updated the language in f62abd87d5ffb2368750555ac56448f20e6699a5

**Comment by kwin** [comment]
Thanks for the answer @justinedelson 

Regarding 
> 1. This is also an implementation detail

That means that security variables can be exclusively used in OSGi configurations (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/deploying/configuring-osgi.html?lang=en#secret-configuration-values)? That is a shame. I would love to leverage that also e.g. in Context-Aware configuration and some other places. I probably then need to rebuild the logic from https://github.com/apache/felix-dev/tree/master/configadmin-plugins/interpolation#secrets-lookup to use it outside OSGi configurations (including leveraging the framework property `org.apache.felix.configadmin.plugin.interpolation.secretsdir` and `org.apache.felix.configadmin.plugin.interpolation.file.encoding`) to figure out where those secrets are located....

3. Thanks for the update, much clearer now. But still I am unsure what 
> encrypted at rest
means, but maybe this is just because I am not a native English speaker....

**Comment by justinedelson** [comment]
@kwin Being able to use environment variables in CA Config (or other places) would certainly be a valid feature request for AEM. The Cloud Manager API is just concerned with how the variables are set (or unset).

> encrypted at rest

This seems to be a commonly used phrase, e.g. https://docs.microsoft.com/en-us/azure/security/fundamentals/encryption-atrest#what-is-encryption-at-rest But if you have ideas for a different phrasing, happy to include it.
