### ISSUE TITLE
Document endpoints for managing IP whitelisting, TLS certificates  and domains

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#27]
The Cloud Manager UI now provides access to the management capabilities for IP whitelists, domains and certificates.

According to https://github.com/AdobeDocs/cloudmanager-api-docs/blob/master/README.md

> The Cloud Manager API enables Cloud Manager customers to interact with the same underlying capabilities exposed through the web UI in a fully programmatic fashion.

I don't yet see a documentation for this functionality in https://github.com/AdobeDocs/cloudmanager-api-docs/blob/master/swagger-specs/api.yaml yet.

**Comment by kwin** [comment]
This is partially solved by https://github.com/AdobeDocs/cloudmanager-api-docs/commit/237e8ab239b9182aeff0ab56d0c4022260b1e58d. The only thing missing is how to add new certificates.

**Comment by justinedelson** [comment]
The missing element was added in fe787b371768014874bc2352a5a3fbac8d0caae9
