### ISSUE TITLE
Provide endpoint for updating environments

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#29]
The Cloud Manager UI allows to update non-PROD environments to a newer AEM version (in case one is available). The same should be possible via API as well.

If this is already possible via https://www.adobe.io/apis/experiencecloud/cloud-manager/api-reference.html#/Pipelines/patchPipeline this should be clarified in there.

**Comment by justinedelson** [comment]
This is not available and, as a result, is not documented.

**Comment by kwin** [comment]
Then probably this sentence from https://github.com/AdobeDocs/cloudmanager-api-docs/blob/master/README.md should be adjusted:

> The Cloud Manager API enables Cloud Manager customers to interact with the same underlying capabilities exposed through the web UI in a fully programmatic fashion. 

As long as the Cloud Manager Web UI is using other (non public) endpoints, there should be a notice of that fact in the readme.

**Comment by kwin** [comment]
For the record: The extension of the Cloud Manager API for the AEM version update is now tracked in feature request CMGR-20046 at Adobe.
