### ISSUE TITLE
Document necessary permissions for managing domains, certificates and IP whitelists

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#30]
### Documentation Location

https://github.com/AdobeDocs/cloudmanager-api-docs/blob/master/permissions.md

### Issue Description

The new endpoints added in https://github.com/AdobeDocs/cloudmanager-api-docs/commit/237e8ab239b9182aeff0ab56d0c4022260b1e58d are not listed there, so it is unclear which roles are allowed to perform which operations.

**Comment by justinedelson** [comment]
These are now listed on https://www.adobe.io/experience-cloud/cloud-manager/guides/getting-started/permissions
