### ISSUE TITLE
Event field "activitystreams:objectType" missing from ended and started events 

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#31]
I have received the following JSON

```
{
  "event_id": "8363b0e5-bfb7-4c95-867d-abbc30b9b456",
  "event": {
    "@id": "urn:oeid:cloudmanager:52c76181-8162-417c-ac48-bc9c410576e3",
    "@type": "https://ns.adobe.com/experience/cloudmanager/event/ended",
    "activitystreams:published": "2021-02-23T09:46:33.908Z",
    "activitystreams:to": {
      "@type": "xdmImsOrg",
      "xdmImsOrg:id": "274B36465AD0972F0A495EA1@AdobeOrg"
    },
    "activitystreams:object": {
      "@id": "https://cloudmanager.adobe.io/api/program/29008/pipeline/1662149/execution/319578/phase/471615/step/821373",
      "@type": "https://ns.adobe.com/experience/cloudmanager/execution-step-state"
    },
    "xdmEventEnvelope:objectType": "https://ns.adobe.com/experience/cloudmanager/execution-step-state"
  }
}
```

According to https://github.com/AdobeDocs/cloudmanager-api-docs/blob/b5c7a0eb35820842752338b9b31b484565742c93/swagger-specs/events.yaml#L126 there is supposed to be an `activitystreams:objectType` field as well. Probably this has been renamed to `xdmEventEnvelope:objectType`. This should be reflected in the YAML spec. It seems to affect all Cloud Manager events.

**Comment by justinedelson** [comment]
This wasn't renamed; it was just a bad copy/paste. This is correctly documented elsewhere (https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/receiving-events.md), just wrong in the swagger.
