### ISSUE TITLE
Fix permission for cancelPipelineExecutionStep for Program Manager

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/cloudmanager-api-docs#33]
### Documentation Location
The permissions table at https://www.adobe.io/apis/experiencecloud/cloud-manager/docs.html#!AdobeDocs/cloudmanager-api-docs/master/permissions.md states that `Program Manager` role can cancel pipeline executions.

When using `adobe-cloudmanager-cli` I get

```
cloudmanager:current-execution:cancel 1662149 --programId 29008 --imsContextName program-29008
cancelling execution... [CloudManagerSDK:ERROR_CANCEL_EXECUTION] Cannot cancel execution: https://cloudmanager.adobe.io/api/program/29008/pipeline/1662149/execution/354881/phase/552672/step/972788/cancel (403 Forbidden) - Access Denied(s): Missing permission
```

With the same credentials I can start new execution without any issues, although both operations should be allowed for the same roles.
My underlying service user has product profile `Cloud Manager - Program Manager Role`

**Comment by kwin** [comment]
@justinedelson Do you have a idea whether this is a bug in the implementation or a documentation error?

**Comment by justinedelson** [comment]
Sorry for the delay @kwin. There is some subtly here that is not well-reflected in the documentation currently. Program Managers can cancel waiting steps (i.e. the approval step), but not running steps. In this case, I believe this was a build step. I tried to make this clearer in f976eec2ba956a4f279676ad37409b2bb771ed05 but not sure the formatting will show up correctly so leaving this open for now.

**Comment by kwin** [comment]
Thanks for the update. That explains the behaviour.

**Comment by justinedelson** [comment]
formatting isn't great on that table, but it's IMO good enough. thanks for the reminder on this.
