### ISSUE TITLE
Change dispatcher flush path 

### ISSUE THREAD

**Issue by teodik** [AdobeDocs/cloudmanager-api-docs#7]
### Issue Description

Is there a way to change the "dispatcher configuration" in Cloud Manager pipeline via API? 

I tried "PATCH https://cloudmanager.adobe.io/api/program/{programID}/pipeline/{pipelineID}" and include the below JSON in API body (the path are bold). The response code is 200, but no changes happen in pipeline:

{
    "name": "{Name of the pipeline}",
    "phases": [
        {
            "name": "{Name of the phase}",
            "type": "{type of the pase}",
            "environmentId": "{ID}",
            "assetCollectionId": "{ID}",
            "environmentType": "{ID}",
            "steps": [
                {
                    "name": "{Step Name}",
                    "options": {
                        "dispatcherCacheInvalidationPaths": [],
                        "dispatcherCacheFlushPaths": [
                            **"/conf/{PATH}",
                            "/content/{PATH}",
                            "/etc",
                            "/etc.clientlibs",
                            "/home",
                            "/libs"**
                        ],
                        "skipDetachingDispatchers": true
                    }
                },
                {
                    "name": "approval"
                },
                {
                    "name": "loadTest",
                    "options": {
                        "popularPagesWeight": {number},
                        "otherPagesWeight": {number},
                        "newPagesWeight": {number}
                    }
                },
                {
                    "name": "assetsTest",
                    "options": {
                        "imageAssetsWeight": {number},
                        "pdfAssetsWeight": {number}
                    }
                }
            ]
        }
    ]
}

**Comment by justinedelson** [comment]
This is not available in the API. It is being considered for a future release and will be documented at that point.
